### ISSUE TITLE
조건에 따라서 게임이 종료될 수 있게 하는 기능

### ISSUE THREAD

**Issue by yhs0602** [thiEFcat/TSystem#1]
라이프가 0이 된다던가 퍼펙트 미만 판정을 내면 폭사하는 게임 모드 지원도 하면 좋을 거 같아요

**Comment by HolySkyMin** [comment]
0.2.0부터 `JudgeBasis.customJudgeAction` (Type `Action<JudgeType, bool>`)이 제공되며, 이를 활용해 라이프 시스템 등을 직접 구현 가능합니다. (`ExampleLifeSystem` 참고)
