### ISSUE TITLE
외부에서 채보 가져오기

### ISSUE THREAD

**Issue by yhs0602** [thiEFcat/TSystem#2]
- linearbeat: `https://linearbeats.jp/lite/search.php?keyword=` 에서 곡 리스트 전부 얻어오기, 
`https://linearbeats.jp/LBServerN/mapdata.php?mapid=$id"`에서 곡 채보 가져오기 가능
- 뱅드림: `https://github.com/BanGround/BanGround-Player/tree/master/api` 에 따르면 bestdori에서 채보와 mp3 등 정보 얻어오기 가능
들을 이용하여, 소스를 불러올 수 있게 하고,

bangbangboom이나 bestdori, linearbeat채보, 그리고 osu, DelesteSimulator 등 여러 채보를 twx로 변환 또는 임포트 하는 기능을 넣으면 좋을 것 같아요

**Comment by HolySkyMin** [comment]
* 온라인에서 채보를 얻어오는 기능은 원칙적으로 TSystem을 import한 각 게임에서 해야 하는 일이라고 판단하므로, 굳이 TSystem에 추가할 생각은 없습니다.
* 채보 변환은 생각해볼 만하긴 한데(개인적으로 이것도 각 게임에서 해야 할 일이라고 생각), 작업 우선순위를 둔다면 아마 가장 나중으로 밀릴듯 합니다.

**Comment by yhs0602** [comment]
현재 스토어에 올라와있는 Tempest Wave는 TSystem과는 다른 것인가요?

**Comment by HolySkyMin** [comment]
Tempest Wave는 TSystem을 활용(import)한 하나의 게임이지 TSystem 그 자체는 아닙니다. (비록 TSystem의 레퍼런스 클라이언트 역할을 하고는 있지만)
